### REGISTER
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
"firstName": "Muhamed",
"lastName": "Lemes",
 "email": "muhamed1@gmail.com",
  "password": "12345",
  "role": "admin"
}

### 
###LOGIN
POST http://localhost:4000/api/auth/login
Content-Type: application/json 

{
 "email": "dzana@gmail.com",
  "password": "12345"
}

### EDIT USER
PUT http://localhost:4000/api/user/edit/646f61a30ec31297776e58d3
Content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc0YmI1NDdjY2Y1ZmZiOWYxMTA5OTciLCJmaXJzdE5hbWUiOiJNdWhhbWVkIiwibGFzdE5hbWUiOiJMZW1lcyIsInJvbGUiOiJ1c2VyIiwidGltZSI6MTY4NTM3MTczNzI5NCwiaWF0IjoxNjg1MzcxNzM3LCJleHAiOjE2ODUzNzE3Njd9.kbRj6jgU6L4iugVdEKk4lQZU4GPUzdc3KTzBpuN72eQ
