### GET SINGLE COMMENT
GET http://localhost:4000/api/comments/649005d0e770ff78d36a599e

### GET COMMENTS BY POST ID
GET http://localhost:4000/api/comments/post/644aedace62d6eb764d77786

###ADD COMMENT
POST http://localhost:4000/api/comments/add/644b7dabf66cb80c55317804
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc0YmEzODkyOTQ4NDY1YzNiNzRlMDciLCJmaXJzdE5hbWUiOiJBaG1lZCIsImxhc3ROYW1lIjoiTGVtZXMiLCJyb2xlIjoidXNlciIsInRpbWUiOjE2ODcxNjAyMzc4MzMsImlhdCI6MTY4NzE2MDIzNywiZXhwIjoxNjg3MjQ2NjM3fQ.qQnmFqE4tYZM1yOkJ785GjuxJKH5moM_AtIlY5bz5x8
Content-Type: application/json

{
    "body": "Ovo je neki komentar!!!!",
}

### EDIT COMMENT
PUT http://localhost:4000/api/comments/644b7dabf66cb80c553177fb
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk4NDcxZjZhYmZmMzE3MTExZGY1ODAiLCJmaXJzdE5hbWUiOiJBaG1lZCIsImxhc3ROYW1lIjoiTGVtZcWhIiwicm9sZSI6InVzZXIiLCJ0aW1lIjoxNjg4MzgyNjIxODU0LCJpYXQiOjE2ODgzODI2MjEsImV4cCI6MTY4ODQ2OTAyMX0.h_n-3-5YsVw6sb7agh5_fwI4XANs4XgEiH7iLflGUPs
Content-Type: application/json

{
  "body": "Drugi user edituje komentar!!!"
}

### DELETE COMMENT
DELETE http://localhost:4000/api/comments/644b7dabf66cb80c55317804
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhjNmRhN2M5YWU0MjI0NzVlNmRiMDEiLCJmaXJzdE5hbWUiOiJNdWhhbWVkIiwibGFzdE5hbWUiOiJMZW1lcyIsInJvbGUiOiJhZG1pbiIsInRpbWUiOjE2ODY5MjQ3MjgyMzksImlhdCI6MTY4NjkyNDcyOCwiZXhwIjoxNjg3MDExMTI4fQ.SjbaS3eWBXntMLO3D5TB4s3IynW31gQHRMslN5EpeTo
Content-Type: application/json