### ADD MESSAGE
POST http://localhost:4000/api/messages/addMessage/646e514e4611dc2bdddb7b7a
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDkyZWExMTYzZWUwYmM0YTQ1YTcyYjciLCJmaXJzdE5hbWUiOiJNdWhhbWVkIiwibGFzdE5hbWUiOiJMZW1lcyIsInJvbGUiOiJhZG1pbiIsInRpbWUiOjE2ODczNDk3OTYzNjQsImlhdCI6MTY4NzM0OTc5NiwiZXhwIjoxNjg3NDM2MTk2fQ.KI0PEK738AauZhbwqkkfQmSLkeV58G2YT4Boy3qNpBg

{
  "message": "Nova poruka !!"
}

### SENT MESSAGES
GET http://localhost:4000/api/messages/sentMessages
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDkyZWExMTYzZWUwYmM0YTQ1YTcyYjciLCJmaXJzdE5hbWUiOiJNdWhhbWVkIiwibGFzdE5hbWUiOiJMZW1lcyIsInJvbGUiOiJhZG1pbiIsInRpbWUiOjE2ODczNDk3OTYzNjQsImlhdCI6MTY4NzM0OTc5NiwiZXhwIjoxNjg3NDM2MTk2fQ.KI0PEK738AauZhbwqkkfQmSLkeV58G2YT4Boy3qNpBg


### RECEIVED MESSAGES
GET http://localhost:4000/api/messages/receivedMessages
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZlNTE0ZTQ2MTFkYzJiZGRkYjdiN2EiLCJmaXJzdE5hbWUiOiJab3JhbmtvdmljIiwibGFzdE5hbWUiOiJTcmRqYW5vdmljY2NjIiwicm9sZSI6ImFkbWluIiwidGltZSI6MTY4NzM1MDM5NDI5NiwiaWF0IjoxNjg3MzUwMzk0LCJleHAiOjE2ODc0MzY3OTR9.TKpAZ2PScuoyRpIN10nQyqApyDMUC9RVMfoz-fCPNo4

