### GET ALL POSTS
GET http://localhost:4000/api/posts/all?page=2&limit=2

### GET USER POSTS
GET http://localhost:4000/api/posts/6498471f6abff317111df580

### GET SINGLE POST
GET http://localhost:4000/api/posts/singlePost/644aedace62d6eb764d77785

### GET POST BY TAGS
GET http://localhost:4000/api/posts/filter?tags=magical&tags=classic

### SEARCH POST
GET http://localhost:4000/api/posts/search?q=first


### ADD NEW POST
POST http://localhost:4000/api/posts/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk4NDcxZjZhYmZmMzE3MTExZGY1ODAiLCJmaXJzdE5hbWUiOiJBaG1lZCIsImxhc3ROYW1lIjoiTGVtZcWhIiwicm9sZSI6InVzZXIiLCJ0aW1lIjoxNjg4MTA4MjQ1NTk1LCJpYXQiOjE2ODgxMDgyNDUsImV4cCI6MTY4ODE5NDY0NX0.shsDZtxRupqfqLZV2r9ytGsPddclFRa9pMvd0jv7dtY

{
    "body": "Test 4 za delete",
    "title": "Test 4 za delete",
    "image": "Neka slika",
    "tags": {"name": "neki tag"}
}

### EDIT POST
PUT http://localhost:4000/api/posts/648f229b463ee6d50109e8e2
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc0YmEzODkyOTQ4NDY1YzNiNzRlMDciLCJmaXJzdE5hbWUiOiJBaG1lZCIsImxhc3ROYW1lIjoiTGVtZXMiLCJyb2xlIjoidXNlciIsInRpbWUiOjE2ODcxMDEzNTI4NTEsImlhdCI6MTY4NzEwMTM1MiwiZXhwIjoxNjg3MTg3NzUyfQ.tdH4-jmud4L28sOvl30f7EnEenp36XNy_s3eK8uNgHk

{
    "body": "Dave sada!"
}

###DELETE POST
DELETE http://localhost:4000/api/posts/649011bbf2eaa09013aeb857
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc0YmEzODkyOTQ4NDY1YzNiNzRlMDciLCJmaXJzdE5hbWUiOiJBaG1lZCIsImxhc3ROYW1lIjoiTGVtZXMiLCJyb2xlIjoidXNlciIsInRpbWUiOjE2ODcxNjMwNzU2MzYsImlhdCI6MTY4NzE2MzA3NSwiZXhwIjoxNjg3MjQ5NDc1fQ.NbNU9QVMskvg8_st5kS6i-9HWXjuM_FkKESvWkFHoeo
