### GET ALL POSTS
GET http://localhost:4000/api/posts/all?page=2&limit=2

### GET SINGLE POST
GET http://localhost:4000/api/posts/648f229b463ee6d50109e8e2

### ADD NEW POST
POST http://localhost:4000/api/posts/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc0YmEzODkyOTQ4NDY1YzNiNzRlMDciLCJmaXJzdE5hbWUiOiJBaG1lZCIsImxhc3ROYW1lIjoiTGVtZXMiLCJyb2xlIjoidXNlciIsInRpbWUiOjE2ODcxMDEzNTI4NTEsImlhdCI6MTY4NzEwMTM1MiwiZXhwIjoxNjg3MTg3NzUyfQ.tdH4-jmud4L28sOvl30f7EnEenp36XNy_s3eK8uNgHk
{
    "body": "Test!",
    "title": "Neki drugi title",
    "image": "Neka slika",
    "tags": {"name": "neki tag"}
}

### EDIT POST
PUT http://localhost:4000/api/posts/648f229b463ee6d50109e8e2
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc0YmEzODkyOTQ4NDY1YzNiNzRlMDciLCJmaXJzdE5hbWUiOiJBaG1lZCIsImxhc3ROYW1lIjoiTGVtZXMiLCJyb2xlIjoidXNlciIsInRpbWUiOjE2ODcxMDEzNTI4NTEsImlhdCI6MTY4NzEwMTM1MiwiZXhwIjoxNjg3MTg3NzUyfQ.tdH4-jmud4L28sOvl30f7EnEenp36XNy_s3eK8uNgHk

{
    "body": "Dave sada!"
}