### GET ALL USERS
GET http://localhost:4000/api/user

### GET SINGLE USER
http://localhost:4000/api/user/6474ba3892948465c3b74e07

### SIGNUP USER
POST http://localhost:4000/api/user/signup
Content-Type: application/json

{
  "firstName": "Ahmed",
  "lastName": "Lemes",
  
}

### EDIT USER
PUT http://localhost:4000/api/user/edit/6474ba3892948465c3b74e07
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhjNmRhN2M5YWU0MjI0NzVlNmRiMDEiLCJmaXJzdE5hbWUiOiJNdWhhbWVkIiwibGFzdE5hbWUiOiJMZW1lcyIsInJvbGUiOiJhZG1pbiIsInRpbWUiOjE2ODcxNzQwNjk5NzgsImlhdCI6MTY4NzE3NDA2OSwiZXhwIjoxNjg3MjYwNDY5fQ.vk5Rp8KD3xvnzesWyAn_ZUtIIZe3rHGlBilu4_mctEI

{
  "firstName": "Ahmed"
}